<?php
use Phalcon\Flash\Session as FlashSession;
$flash = new FlashSession();
?>

<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //Meta-Tags -->
	
	
	<link href="<?=$base_url?>/public/css/login.css" rel="stylesheet" type="text/css" media="all"/>
<div class="signupform">
	<div class="container">
		<!-- main content -->
		<div class="agile_info">
			<div class="w3l_form">
				<div class="left_grid_info">
					<h1>Manage Your Business Account</h1>
					<p>Donec dictum nisl nec mi lacinia, sed maximus tellus eleifend. Proin molestie cursus sapien ac eleifend.</p>
					<img src="<?=$base_url?>/public/images/login/image.jpg" alt="" />
				</div>
			</div>
			<div class="w3_info">
				<h2>Login to your Account</h2>
				<p>Enter your details to login.</p>
				<form action="" method="post">
					<label>User Name</label>
					<div class="input-group">
					
						<input type="text" placeholder="User Name" name = "username" required=""> 
					</div>
					<label>Password</label>
					<div class="input-group">
	
						<input type="Password" placeholder="Password" required="" name = "password">
                    </div>
                        <?php $err_mes = $flash->getMessages("error") ;?>
                        <?php if (!empty($err_mes)) : ?>
                        <?php foreach ($err_mes as $value):?>
                        <p class="account"><a ><?=$value?></a></p> <br>
                        <?php endforeach ;?>
                        <?php endif;?>
						<button class="btn btn-danger btn-block" type="submit">Login</button >                
				</form>
			
		
			</div>
		</div>
		<!-- //main content -->
	</div>
	<!-- footer -->
	<div class="footer">
		<p>&copy; 2019 Business login form. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="blank">CuongPhan</a></p>
	</div>